# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


finerAct:
 loanUrl: 'https://api.lnddo.loan/fineract-provider/api/v1/loans'
 submitUrl: 'https://api.lnddo.loan/fineract-provider/api/v1/loans'
 clientUrl: 'https://api.lnddo.loan/fineract-provider/api/v1/clients'

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
#
# More documentation is available at:
# ===================================================================

# application:
